from django.urls import path

from .views import (
    EmailTemplateDetailView,
    EmailTemplateListView,
    EmailTemplatePreviewView,
    EmailTemplateSyncView,
    EmailTemplateSendTestView,
    MailSettingsAuditCsvExportView,
    CommunicationPreferenceMeView,
    MailSettingsAuditListView,
    MailSettingsTestView,
    MailSettingsView,
    MailgunWebhookView,
    MarketingOneClickUnsubscribeView,
    NotificationsBaselineView,
    WhatsAppContactMeView,
    WhatsAppHealthView,
    WhatsAppMetaWebhookView,
    WhatsAppTemplateMapDetailView,
    WhatsAppTemplateMapListView,
    WhatsAppSettingsView,
    WhatsAppSettingsTestView,
    WhatsAppRecentDeliveriesView,
    WhatsAppTemplateMapSubmitView,
    WhatsAppTemplateMapApproveView,
    WhatsAppTemplateMapRejectView,
    WhatsAppTemplateMapAuditCsvExportView,
    WhatsAppTemplateSlaAuditListView,
    WhatsAppTemplateSlaAuditCsvExportView,
)


urlpatterns = [
    path("webhooks/mailgun/", MailgunWebhookView.as_view(), name="communications_mailgun_webhook"),
    path("webhooks/whatsapp/meta/", WhatsAppMetaWebhookView.as_view(), name="communications_whatsapp_meta_webhook"),
    path("preferences/me/", CommunicationPreferenceMeView.as_view(), name="communications_preference_me"),
    path("whatsapp/me/", WhatsAppContactMeView.as_view(), name="communications_whatsapp_me"),
    path("settings/whatsapp/templates/", WhatsAppTemplateMapListView.as_view(), name="communications_whatsapp_templates_list"),
    path("settings/whatsapp/templates/<int:map_id>/", WhatsAppTemplateMapDetailView.as_view(), name="communications_whatsapp_templates_detail"),
    path("settings/whatsapp/templates/<int:map_id>/submit/", WhatsAppTemplateMapSubmitView.as_view(), name="communications_whatsapp_templates_submit"),
    path("settings/whatsapp/templates/<int:map_id>/approve/", WhatsAppTemplateMapApproveView.as_view(), name="communications_whatsapp_templates_approve"),
    path("settings/whatsapp/templates/<int:map_id>/reject/", WhatsAppTemplateMapRejectView.as_view(), name="communications_whatsapp_templates_reject"),
    path("settings/whatsapp/templates/export/", WhatsAppTemplateMapAuditCsvExportView.as_view(), name="communications_whatsapp_templates_export"),
    path("settings/whatsapp/template-sla-audits/", WhatsAppTemplateSlaAuditListView.as_view(), name="communications_whatsapp_template_sla_audits"),
    path("settings/whatsapp/template-sla-audits/export/", WhatsAppTemplateSlaAuditCsvExportView.as_view(), name="communications_whatsapp_template_sla_audits_export"),
    path("settings/whatsapp/health/", WhatsAppHealthView.as_view(), name="communications_whatsapp_health"),
    path("settings/notifications/baseline/", NotificationsBaselineView.as_view(), name="communications_notifications_baseline"),
    path("unsubscribe/one-click/", MarketingOneClickUnsubscribeView.as_view(), name="communications_unsubscribe_one_click"),
    path("settings/mailgun/", MailSettingsView.as_view(), name="communications_mailgun_settings"),
    path("settings/whatsapp/", WhatsAppSettingsView.as_view(), name="communications_whatsapp_settings"),
    path("settings/mailgun/test/", MailSettingsTestView.as_view(), name="communications_mailgun_settings_test"),
    path("settings/whatsapp/test/", WhatsAppSettingsTestView.as_view(), name="communications_whatsapp_settings_test"),
    path("settings/whatsapp/deliveries/", WhatsAppRecentDeliveriesView.as_view(), name="communications_whatsapp_recent_deliveries"),
    path("settings/mailgun/audits/", MailSettingsAuditListView.as_view(), name="communications_mailgun_settings_audits"),
    path("settings/mailgun/audits/export/", MailSettingsAuditCsvExportView.as_view(), name="communications_mailgun_settings_audits_export"),
    path("settings/email-templates/", EmailTemplateListView.as_view(), name="communications_email_templates_list"),
    path("settings/email-templates/sync/", EmailTemplateSyncView.as_view(), name="communications_email_templates_sync"),
    path("settings/email-templates/<slug:slug>/", EmailTemplateDetailView.as_view(), name="communications_email_templates_detail"),
    path("settings/email-templates/<slug:slug>/preview/", EmailTemplatePreviewView.as_view(), name="communications_email_templates_preview"),
    path("settings/email-templates/<slug:slug>/test/", EmailTemplateSendTestView.as_view(), name="communications_email_templates_test"),
]
