# Generated by Django 5.2.9 on 2025-12-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('RETIRED', 'Retirado'), ('GRADUATED', 'Graduado')], default='ACTIVE', max_length=20)),
                ('origin_school', models.CharField(blank=True, max_length=200, verbose_name='Procedencia')),
                ('final_status', models.CharField(blank=True, max_length=50, verbose_name='Promoción')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Cédula')),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_main_guardian', models.BooleanField(default=False)),
                ('is_head_of_household', models.BooleanField(default=False, verbose_name='Cabeza de familia')),
            ],
        ),
    ]
