# Generated by Django 5.2.9 on 2025-12-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_achievement_evaluationcomponent_assessment_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('place_of_issue', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('nationality', models.CharField(blank=True, default='Colombiana', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio/Vereda')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('living_with', models.CharField(blank=True, max_length=200, verbose_name='Con quién vive')),
                ('stratum', models.CharField(blank=True, max_length=2, verbose_name='Estrato')),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('sisben_score', models.CharField(blank=True, max_length=20, verbose_name='SISBÉN')),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('is_victim_of_conflict', models.BooleanField(default=False, verbose_name='Víctima del conflicto')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('disability_description', models.TextField(blank=True, verbose_name='Descripción discapacidad')),
                ('disability_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de discapacidad')),
                ('support_needs', models.TextField(blank=True, verbose_name='Apoyos requeridos')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Cédula')),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_main_guardian', models.BooleanField(default=False)),
                ('is_head_of_household', models.BooleanField(default=False, verbose_name='Cabeza de familia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('RETIRED', 'Retirado'), ('GRADUATED', 'Graduado')], default='ACTIVE', max_length=20)),
                ('origin_school', models.CharField(blank=True, max_length=200, verbose_name='Procedencia')),
                ('final_status', models.CharField(blank=True, max_length=50, verbose_name='Promoción')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
