# Generated by Django 5.2.9 on 2025-12-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty_type', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro'), ('REINGRESO', 'Reingreso'), ('OTRO', 'Otro')], max_length=20)),
                ('date', models.DateField()),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
