# Generated by Django 5.2.9 on 2025-12-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('core', '0002_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de documento')),
                ('place_of_issue', models.CharField(blank=True, max_length=100, verbose_name='Lugar de expedición')),
                ('nationality', models.CharField(blank=True, default='Colombiana', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio/Vereda')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('living_with', models.CharField(blank=True, max_length=200, verbose_name='Con quién vive')),
                ('stratum', models.CharField(blank=True, max_length=2, verbose_name='Estrato')),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('sisben_score', models.CharField(blank=True, max_length=20, verbose_name='SISBÉN')),
                ('eps', models.CharField(blank=True, max_length=100)),
                ('is_victim_of_conflict', models.BooleanField(default=False, verbose_name='Víctima del conflicto')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('disability_description', models.TextField(blank=True, verbose_name='Descripción discapacidad')),
                ('disability_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de discapacidad')),
                ('support_needs', models.TextField(blank=True, verbose_name='Apoyos requeridos')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias/Restricciones')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Contacto Emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Emergencia')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='Parentesco Emergencia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Foto')),
                ('financial_status', models.CharField(choices=[('SOLVENT', 'Paz y Salvo'), ('DEBT', 'En Mora')], default='SOLVENT', max_length=20, verbose_name='Estado Financiero')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.grade'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.group'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='students.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('IDENTITY', 'Documento de Identidad'), ('VACCINES', 'Carnet de Vacunas'), ('EPS', 'Certificado EPS'), ('ACADEMIC', 'Certificado Académico Anterior'), ('PHOTO', 'Foto Tipo Documento'), ('OTHER', 'Otro')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty_type', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro'), ('REINGRESO', 'Reingreso'), ('OTRO', 'Otro')], max_length=20)),
                ('date', models.DateField()),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
