# Generated by Django 5.2.9 on 2025-12-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_academiclevel_group_campus_grade_level'),
        ('core', '0001_initial'),
        ('students', '0002_studentnovelty'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alergias/Restricciones'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono Emergencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parentesco Emergencia'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('IDENTITY', 'Documento de Identidad'), ('VACCINES', 'Carnet de Vacunas'), ('EPS', 'Certificado EPS'), ('ACADEMIC', 'Certificado Académico Anterior'), ('PHOTO', 'Foto Tipo Documento'), ('OTHER', 'Otro')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
        ),
    ]
