# Generated by Django 5.2.9 on 2025-12-31 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_grade_options_grade_ordinal_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(blank=True, help_text='Fecha de ingreso al año lectivo (útil para estudiantes que entran a mitad de año).', null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.CreateModel(
            name='ConditionalPromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_subject_ids', models.JSONField(blank=True, default=list)),
                ('pending_area_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('CLEARED', 'Aprobado / superado'), ('FAILED', 'No superado')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_period', models.ForeignKey(blank=True, help_text='Periodo límite (normalmente el primer periodo del año siguiente).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.period')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_plan', to='students.enrollment')),
                ('source_enrollment', models.ForeignKey(blank=True, help_text='Matrícula de origen (año anterior) desde la cual se definió la promoción condicional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_plans_created_from', to='students.enrollment')),
            ],
            options={
                'verbose_name': 'Plan de promoción condicional (PAP)',
                'verbose_name_plural': 'Planes de promoción condicional (PAP)',
            },
        ),
    ]
