# Generated by Django 5.2.9 on 2025-12-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='financial_status',
            field=models.CharField(choices=[('SOLVENT', 'Paz y Salvo'), ('DEBT', 'En Mora')], default='SOLVENT', max_length=20, verbose_name='Estado Financiero'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Foto'),
        ),
    ]
