# Generated by Django 5.2.9 on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_certificateissue_revenue_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateissue",
            name="pdf_private_relpath",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="certificateissue",
            name="pdf_private_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="certificateissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("ISSUED", "Emitido"),
                    ("REVOKED", "Revocado"),
                ],
                default="ISSUED",
                max_length=10,
            ),
        ),
    ]
