# Generated by GitHub Copilot

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_certificateissue_private_pdf_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="identity_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="family_identity_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Documento de identidad (archivo)",
            ),
        ),
    ]
