# Generated by Django 5.2.9 on 2026-01-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_student_photo_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("IDENTITY", "Documento de Identidad"),
                    ("GUARDIAN_IDENTITY", "Documento de identidad del acudiente"),
                    ("VACCINES", "Carnet de Vacunas"),
                    ("EPS", "Certificado EPS"),
                    ("ACADEMIC", "Certificado Académico Anterior"),
                    ("PHOTO", "Foto Tipo Documento"),
                    ("OTHER", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
