# Generated by Django 5.2.11 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_alter_studentdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="identity_document_private_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="familymember",
            name="identity_document_private_relpath",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="file_private_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="file_private_relpath",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="student_documents/"),
        ),
    ]
