# Generated by Django 5.2.9 on 2026-01-18 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("DUMMY", "Dummy (prueba)")], max_length=64
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En proceso"),
                            ("SUCCEEDED", "Completado"),
                            ("FAILED", "Fallido"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "output_relpath",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "output_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "output_content_type",
                    models.CharField(default="application/pdf", max_length=128),
                ),
                ("output_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
