# Generated by Django 5.2.9 on 2026-01-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('DUMMY', 'Dummy (prueba)'), ('ACADEMIC_PERIOD_ENROLLMENT', 'Informe académico (matrícula/periodo)')], max_length=64),
        ),
    ]
