# Generated by Django 5.2.9 on 2026-01-18 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportjob_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('DUMMY', 'Dummy (prueba)'), ('ACADEMIC_PERIOD_ENROLLMENT', 'Informe académico (matrícula/periodo)'), ('ACADEMIC_PERIOD_GROUP', 'Informe académico (grupo/periodo)'), ('DISCIPLINE_CASE_ACTA', 'Acta de caso disciplinario'), ('ATTENDANCE_MANUAL_SHEET', 'Planilla de asistencia (manual)'), ('ENROLLMENT_LIST', 'Reporte de matriculados')], max_length=64),
        ),
        migrations.CreateModel(
            name='ReportJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.reportjob')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
