# Generated by Django 5.2.9 on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_reportjob_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportjob",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DUMMY", "Dummy (prueba)"),
                    ("ACADEMIC_PERIOD_ENROLLMENT", "Informe académico (matrícula/periodo)"),
                    ("ACADEMIC_PERIOD_GROUP", "Informe académico (grupo/periodo)"),
                    ("DISCIPLINE_CASE_ACTA", "Acta de caso disciplinario"),
                    ("ATTENDANCE_MANUAL_SHEET", "Planilla de asistencia (manual)"),
                    ("ENROLLMENT_LIST", "Reporte de matriculados"),
                    ("GRADE_REPORT_SHEET", "Planilla imprimible de notas"),
                    ("TEACHER_STATISTICS_AI", "Estadísticas IA (docente)"),
                    ("CERTIFICATE_STUDIES", "Certificado de estudios"),
                ],
                max_length=64,
            ),
        ),
    ]
