# Generated by Django 5.2.9 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_alter_reportjob_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportjob",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DUMMY", "Dummy (prueba)"),
                    (
                        "ACADEMIC_PERIOD_ENROLLMENT",
                        "Informe académico (matrícula/periodo)",
                    ),
                    ("ACADEMIC_PERIOD_GROUP", "Informe académico (grupo/periodo)"),
                    ("ACADEMIC_PERIOD_SABANA", "Sábana de notas (grupo/periodo)"),
                    ("DISCIPLINE_CASE_ACTA", "Acta de caso disciplinario"),
                    ("ATTENDANCE_MANUAL_SHEET", "Planilla de asistencia (manual)"),
                    ("ENROLLMENT_LIST", "Reporte de matriculados"),
                    ("FAMILY_DIRECTORY_BY_GROUP", "Directorio de padres por grados y grupos"),
                    ("GRADE_REPORT_SHEET", "Planilla imprimible de notas"),
                    ("TEACHER_STATISTICS_AI", "Estadísticas IA (docente)"),
                    ("CERTIFICATE_STUDIES", "Certificado de estudios"),
                    (
                        "STUDY_CERTIFICATION",
                        "Certificación académica (constancia de estudio)",
                    ),
                    ("OBSERVER_REPORT", "Observador del estudiante"),
                    ("ACADEMIC_COMMISSION_ACTA", "Acta de compromiso académico"),
                    ("ACADEMIC_COMMISSION_GROUP_ACTA", "Acta grupal de comisión académica"),
                ],
                max_length=64,
            ),
        ),
    ]
