# Generated by Django 5.2.11 on 2026-03-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_reportjob_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicJobRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(max_length=80, unique=True)),
                ('enabled_override', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_key'],
            },
        ),
    ]
