# Generated by Django 5.2.11 on 2026-03-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_periodicjobruntimeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicjobruntimeconfig',
            name='params_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
