# Generated by Django 5.2.11 on 2026-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_periodicjobruntimeconfig_params_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicjobruntimeconfig',
            name='schedule_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
