# Generated by Django 6.0 on 2026-03-05 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('OPTED_OUT', 'Opted out'), ('INVALID_NUMBER', 'Invalid number'), ('NOT_WHATSAPP', 'Not a WhatsApp number'), ('POLICY_BLOCK', 'Policy blocked')], max_length=30)),
                ('provider', models.CharField(default='meta_cloud_api', max_length=50)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=32)),
                ('message_text', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='transactional', max_length=50)),
                ('provider', models.CharField(default='meta_cloud_api', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('recipient_phone', 'idempotency_key'), name='communications_unique_whatsapp_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='meta_cloud_api', max_length=50)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider', 'provider_event_id'), name='communications_unique_whatsapp_provider_event_id')],
            },
        ),
    ]
