# Generated by Django 6.0 on 2026-03-05 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_whatsappsuppression_whatsappcontact_whatsappdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=80, unique=True)),
                ('template_name', models.CharField(max_length=120)),
                ('language_code', models.CharField(default='es_CO', max_length=20)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('authentication', 'Authentication'), ('marketing', 'Marketing')], default='utility', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_template_maps_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
    ]
