# Generated by Django 6.0 on 2026-03-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_whatsapptemplatemap'),
        ('core', '0006_alter_institution_pdf_rector_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappdelivery',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_deliveries', to='core.institution'),
        ),
        migrations.AddField(
            model_name='whatsapptemplatemap',
            name='body_parameter_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsapptemplatemap',
            name='default_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WhatsAppInstitutionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('read', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('suppressed', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_metrics', to='core.institution')),
            ],
            options={
                'ordering': ['-window_end', 'institution_id'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'window_start', 'window_end'), name='communications_unique_whatsapp_institution_metric_window')],
            },
        ),
    ]
