# Generated by Django 6.0 on 2026-03-05 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_whatsappdelivery_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], default='development', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(default='meta_cloud_api', max_length=50)),
                ('graph_base_url', models.URLField(default='https://graph.facebook.com')),
                ('api_version', models.CharField(default='v21.0', max_length=20)),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=120)),
                ('access_token', models.CharField(blank=True, default='', max_length=255)),
                ('app_secret', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_verify_token', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_strict', models.BooleanField(default=True)),
                ('http_timeout_seconds', models.PositiveSmallIntegerField(default=12)),
                ('send_mode', models.CharField(choices=[('template', 'Template'), ('text', 'Text')], default='template', max_length=20)),
                ('template_fallback_name', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('environment',), name='communications_unique_whatsapp_settings_environment')],
            },
        ),
    ]
