# Generated by Django 5.2.11 on 2026-03-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0028_whatsapptemplateslaaudit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="whatsapptemplatemap",
            new_name="communicati_approva_b0e43a_idx",
            old_name="communicatio_approva_becfe2_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsapptemplateslaaudit",
            new_name="communicati_environ_63a7d2_idx",
            old_name="communicatio_environ_88f0af_idx",
        ),
    ]
