# Generated by Django 6.0 on 2026-03-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtype_and_dispatch_dead_letter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_status_bbe6ef_idx',
            old_name='notificatio_status_a86ebf_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_notific_88d138_idx',
            old_name='notificatio_notific_9a6d57_idx',
        ),
    ]
