# Generated by Django 5.2.12 on 2026-03-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_rename_notificatio_status_a86ebf_idx_notificatio_status_bbe6ef_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPlanActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("activity_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operational_plan_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operational_plan_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_operational_plan_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["activity_date", "title", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="operationalplanactivity",
            index=models.Index(fields=["is_active", "activity_date"], name="notificatio_is_acti_5fb763_idx"),
        ),
        migrations.AddIndex(
            model_name="operationalplanactivity",
            index=models.Index(fields=["activity_date", "created_at"], name="notificatio_activit_b7f7a4_idx"),
        ),
    ]
