# Generated by Django 5.2.12 on 2026-03-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_operationalplanactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationalplanactivity',
            new_name='notificatio_is_acti_a4128b_idx',
            old_name='notificatio_is_acti_5fb763_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalplanactivity',
            new_name='notificatio_activit_ee388b_idx',
            old_name='notificatio_activit_b7f7a4_idx',
        ),
    ]
