# Generated by Django 5.2.12 on 2026-03-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_operationalplanactivity_end_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="operationalplanactivity",
            new_name="notificatio_is_acti_7ddebf_idx",
            old_name="notificatio_is_acti_8d7314_idx",
        ),
    ]
