# Generated by Django 5.2.11 on 2026-03-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0009_rename_notificatio_is_acti_8d7314_idx_notificatio_is_acti_7ddebf_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplanactivity",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalplanactivity",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_operational_plan_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationalplanactivity",
            name="completion_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="operationalplanactivity",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="operationalplanactivity",
            index=models.Index(
                fields=["is_active", "is_completed", "activity_date"],
                name="notificatio_is_acti_dce363_idx",
            ),
        ),
    ]
