# Generated by Django 5.2.9 on 2025-12-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de documento')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título Profesional')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('regime', models.CharField(blank=True, choices=[('2277', 'Estatuto 2277 de 1979 (Antiguo)'), ('1278', 'Estatuto 1278 de 2002 (Nuevo)')], max_length=10, null=True, verbose_name='Régimen')),
                ('salary_scale', models.CharField(blank=True, choices=[('1', 'Grado 1'), ('2', 'Grado 2'), ('3', 'Grado 3'), ('4', 'Grado 4'), ('5', 'Grado 5'), ('6', 'Grado 6'), ('7', 'Grado 7'), ('8', 'Grado 8'), ('9', 'Grado 9'), ('10', 'Grado 10'), ('11', 'Grado 11'), ('12', 'Grado 12'), ('13', 'Grado 13'), ('14', 'Grado 14'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D')], max_length=10, verbose_name='Escalafón')),
                ('teaching_level', models.CharField(choices=[('PRESCHOOL', 'Preescolar (20 horas)'), ('PRIMARY', 'Básica Primaria (25 horas)'), ('SECONDARY', 'Básica Secundaria y Media (22 horas)')], default='SECONDARY', max_length=20, verbose_name='Nivel de Enseñanza')),
                ('hiring_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
            ],
        ),
    ]
