# Generated by Django 5.2.9 on 2025-12-03 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título Profesional')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('salary_scale', models.CharField(blank=True, max_length=50, verbose_name='Escalafón')),
                ('hiring_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
            ],
        ),
    ]
