# Generated by Django 5.2.9 on 2025-12-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='regime',
            field=models.CharField(blank=True, choices=[('2277', 'Estatuto 2277 de 1979 (Antiguo)'), ('1278', 'Estatuto 1278 de 2002 (Nuevo)')], max_length=10, null=True, verbose_name='Régimen'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_scale',
            field=models.CharField(blank=True, choices=[('1', 'Grado 1'), ('2', 'Grado 2'), ('3', 'Grado 3'), ('4', 'Grado 4'), ('5', 'Grado 5'), ('6', 'Grado 6'), ('7', 'Grado 7'), ('8', 'Grado 8'), ('9', 'Grado 9'), ('10', 'Grado 10'), ('11', 'Grado 11'), ('12', 'Grado 12'), ('13', 'Grado 13'), ('14', 'Grado 14'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D')], max_length=10, verbose_name='Escalafón'),
        ),
    ]
