# Generated by Django 5.2.9 on 2025-12-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_regime_alter_teacher_salary_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de documento'),
        ),
    ]
