# Generated by Django 5.2.9 on 2025-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(choices=[('PRESCHOOL', 'Preescolar (20 horas)'), ('PRIMARY', 'Básica Primaria (25 horas)'), ('SECONDARY', 'Básica Secundaria y Media (22 horas)')], default='SECONDARY', max_length=20, verbose_name='Nivel de Enseñanza'),
        ),
    ]
