# Generated by Django 5.2.12 on 2026-04-12 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_remove_periodtopic_uniq_period_topic_order_per_load'),
        ('teachers', '0005_teacher_photo_thumb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherstatisticsaianalysis',
            name='uniq_teacher_stats_ai_scope',
        ),
        migrations.AddField(
            model_name='teacherstatisticsaianalysis',
            name='audience',
            field=models.CharField(choices=[('teacher', 'Docente'), ('parents', 'Padres/Acudientes')], default='teacher', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='teacherstatisticsaianalysis',
            constraint=models.UniqueConstraint(fields=('user', 'academic_year', 'period', 'director_mode', 'director_group_id', 'passing_score', 'audience'), name='uniq_teacher_stats_ai_scope'),
        ),
    ]
