# Generated by Django 5.2.9 on 2026-01-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verifiabledocument',
            new_name='verificatio_doc_typ_1472f0_idx',
            old_name='verification_doc_type_8a3d9b_idx',
        ),
        migrations.RenameIndex(
            model_name='verifiabledocument',
            new_name='verificatio_status_c20bbf_idx',
            old_name='verification_status_7fe4c3_idx',
        ),
    ]
