# Generated by Django 5.2.9 on 2026-02-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0003_rename_verification_doc_type_8a3d9b_idx_verificatio_doc_typ_1472f0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifiabledocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("STUDY_CERTIFICATE", "Certificado de estudios"),
                    ("STUDY_CERTIFICATION", "Certificación académica"),
                    ("REPORT_CARD", "Boletín / Informe académico"),
                    ("OBSERVER_REPORT", "Observador del estudiante"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
