# Generated by Django 5.2 on 2026-01-27

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0008_observerannotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoveltyType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NoveltyCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("FILED", "Radicada"),
                            ("IN_REVIEW", "En revisión"),
                            ("PENDING_DOCS", "Pendiente de documentación"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("radicado", models.CharField(blank=True, default="", max_length=32)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_novelty_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "novelty_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="novelties.noveltytype",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novelty_cases",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoveltyReason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "novelty_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reasons",
                        to="novelties.noveltytype",
                    ),
                ),
            ],
            options={
                "ordering": ["novelty_type__name", "name"],
                "unique_together": {("novelty_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="NoveltyCaseTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("FILED", "Radicada"),
                            ("IN_REVIEW", "En revisión"),
                            ("PENDING_DOCS", "Pendiente de documentación"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                            ("CLOSED", "Cerrada"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("FILED", "Radicada"),
                            ("IN_REVIEW", "En revisión"),
                            ("PENDING_DOCS", "Pendiente de documentación"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("EXECUTED", "Ejecutada"),
                            ("CLOSED", "Cerrada"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=24)),
                ("comment", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novelty_case_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="novelties.noveltycase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="noveltycase",
            name="novelty_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="novelties.noveltyreason",
            ),
        ),
        migrations.AddIndex(
            model_name="noveltycase",
            index=models.Index(fields=["student", "status"], name="novelties_n_student_1d4c86_idx"),
        ),
        migrations.AddIndex(
            model_name="noveltycase",
            index=models.Index(fields=["radicado"], name="novelties_n_radicad_79f3f4_idx"),
        ),
    ]
