# Generated by Django 5.2.9 on 2026-01-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novelties", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="noveltycase",
            new_name="novelties_n_student_b36aa1_idx",
            old_name="novelties_n_student_1d4c86_idx",
        ),
        migrations.RenameIndex(
            model_name="noveltycase",
            new_name="novelties_n_radicad_219260_idx",
            old_name="novelties_n_radicad_79f3f4_idx",
        ),
    ]
