# Generated by Django 5.2.9 on 2026-01-27 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_institution_pdf_rector_signature_image"),
        (
            "novelties",
            "0002_rename_novelties_n_student_1d4c86_idx_novelties_n_student_b36aa1_idx_and_more",
        ),
        ("students", "0008_observerannotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoveltyRadicadoCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("last_seq", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="noveltycase",
            name="filed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noveltycase",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institución responsable del radicado y del flujo.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="novelty_cases",
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="noveltycase",
            name="radicado_seq",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noveltycase",
            name="radicado_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="noveltycase",
            constraint=models.UniqueConstraint(
                fields=("institution", "radicado_year", "radicado_seq"),
                name="uniq_novelty_radicado_per_institution_year",
            ),
        ),
        migrations.AddField(
            model_name="noveltyradicadocounter",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="novelty_radicado_counters",
                to="core.institution",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noveltyradicadocounter",
            unique_together={("institution", "year")},
        ),
    ]
