# Generated by Django 5.2.9 on 2026-01-27 22:13

import django.core.validators
import django.db.models.deletion
import novelties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novelties", "0003_noveltyradicadocounter_noveltycase_filed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoveltyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.SlugField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        upload_to=novelties.models.novelty_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("issued_by", models.CharField(blank=True, default="", max_length=200)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "Todos"),
                            ("ADMIN_ONLY", "Solo Admin"),
                            ("COORDINATOR_ONLY", "Solo Coordinación"),
                            ("SECRETARY_ONLY", "Solo Secretaría"),
                        ],
                        default="ALL",
                        max_length=24,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="novelties.noveltycase",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novelty_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "doc_type"],
                        name="novelties_n_case_id_2c384d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NoveltyRequiredDocumentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.SlugField(
                        help_text="Código del tipo de documento (ej. acta_retiro)",
                        max_length=64,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "Todos"),
                            ("ADMIN_ONLY", "Solo Admin"),
                            ("COORDINATOR_ONLY", "Solo Coordinación"),
                            ("SECRETARY_ONLY", "Solo Secretaría"),
                        ],
                        default="ALL",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "novelty_reason",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si se define, la regla aplica solo cuando el caso tenga este motivo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_document_rules",
                        to="novelties.noveltyreason",
                    ),
                ),
                (
                    "novelty_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_document_rules",
                        to="novelties.noveltytype",
                    ),
                ),
            ],
            options={
                "ordering": ["novelty_type__name", "doc_type"],
                "unique_together": {("novelty_type", "novelty_reason", "doc_type")},
            },
        ),
    ]
