# Generated by Django 5.2.9 on 2026-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novelties", "0007_noveltyreversion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="capacitybucket",
            new_name="novelties_c_campus__4f0ea8_idx",
            old_name="novelties_campus_gra_0a8e7f_idx",
        ),
        migrations.AlterField(
            model_name="noveltycasetransition",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("FILED", "Radicada"),
                    ("IN_REVIEW", "En revisión"),
                    ("PENDING_DOCS", "Pendiente de documentación"),
                    ("APPROVED", "Aprobada"),
                    ("REJECTED", "Rechazada"),
                    ("EXECUTED", "Ejecutada"),
                    ("REVERTED", "Revertida"),
                    ("CLOSED", "Cerrada"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="noveltycasetransition",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("FILED", "Radicada"),
                    ("IN_REVIEW", "En revisión"),
                    ("PENDING_DOCS", "Pendiente de documentación"),
                    ("APPROVED", "Aprobada"),
                    ("REJECTED", "Rechazada"),
                    ("EXECUTED", "Ejecutada"),
                    ("REVERTED", "Revertida"),
                    ("CLOSED", "Cerrada"),
                ],
                max_length=24,
            ),
        ),
    ]
