# Generated by Django 5.2.9 on 2026-01-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "novelties",
            "0008_rename_novelties_campus_gra_0a8e7f_idx_novelties_c_campus__4f0ea8_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noveltyexecution",
            name="revert_of",
        ),
    ]
