# Generated by Django 6.0 on 2026-01-15 06:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0014_alter_grade_ordinal_integer_range'),
        ('students', '0005_certificateissue_revenue_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(default=django.utils.timezone.localdate)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.period')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.teacherassignment')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('TARDY', 'Tarde'), ('EXCUSED', 'Excusa')], default='PRESENT', max_length=10)),
                ('tardy_at', models.DateTimeField(blank=True, null=True)),
                ('excuse_reason', models.TextField(blank=True)),
                ('excuse_attachment', models.FileField(blank=True, null=True, upload_to='attendance/excuses/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher_assignment', 'class_date'], name='idx_att_sess_ta_date'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['period', 'class_date'], name='idx_att_sess_period_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('teacher_assignment', 'period', 'class_date', 'sequence'), name='uniq_attendance_session_assignment_period_date_seq'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('created_by', 'client_uuid'), name='uniq_attendance_session_created_by_client_uuid'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['enrollment', 'status'], name='idx_att_rec_enroll_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='idx_att_rec_session_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'enrollment'), name='uniq_attendance_record_session_enrollment'),
        ),
    ]
