# Generated by Django 6.0 on 2025-12-26 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Fecha y hora del hecho')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('narrative', models.TextField(verbose_name='Narrativa de los hechos')),
                ('manual_severity', models.CharField(choices=[('MINOR', 'Leve'), ('MAJOR', 'Grave'), ('VERY_MAJOR', 'Gravísima')], default='MINOR', max_length=20, verbose_name='Clasificación (Manual)')),
                ('law_1620_type', models.CharField(choices=[('I', 'Tipo I'), ('II', 'Tipo II'), ('III', 'Tipo III'), ('UNKNOWN', 'Sin clasificar')], default='UNKNOWN', max_length=10, verbose_name='Clasificación (Ley 1620)')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('DECIDED', 'Decidido'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('notified_guardian_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_text', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_cases_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_cases_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_cases_decided', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_cases', to='students.enrollment', verbose_name='Matrícula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_cases', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EVIDENCE', 'Evidencia'), ('DESCARGOS', 'Descargos'), ('NOTIFICATION', 'Notificación'), ('OTHER', 'Otro')], default='EVIDENCE', max_length=20)),
                ('file', models.FileField(upload_to='discipline_case_attachments/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='discipline.disciplinecase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_case_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Creación'), ('NOTE', 'Nota'), ('NOTIFIED_GUARDIAN', 'Notificación a acudiente'), ('DESCARGOS', 'Descargos'), ('DECISION', 'Decisión'), ('CLOSED', 'Cierre')], max_length=30)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='discipline.disciplinecase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_case_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineCaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ALLEGED_AGGRESSOR', 'Presunto agresor'), ('ALLEGED_VICTIM', 'Presunta víctima'), ('WITNESS', 'Testigo'), ('OTHER', 'Otro')], default='OTHER', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='discipline.disciplinecase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_participations', to='students.student')),
            ],
            options={
                'unique_together': {('case', 'student', 'role')},
            },
        ),
    ]
