# Generated by Django 6.0 on 2025-12-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_disciplinecase_descargos_due_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disciplinecasenotificationlog',
            new_name='discipline__case_id_d915b4_idx',
            old_name='discipline__case_id_3a7830_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinecasenotificationlog',
            new_name='discipline__recipie_d66fa1_idx',
            old_name='discipline__recipie_f926e4_idx',
        ),
    ]
