# Generated by Django 5.2.9 on 2025-12-26 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_rename_discipline__case_id_3a7830_idx_discipline__case_id_d915b4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecase',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='sealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_cases_sealed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='sealed_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
