# Generated by Django 5.2.9 on 2026-01-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0006_convivencia_manual_and_ai_suggestions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disciplinecasedecisionsuggestion',
            new_name='discipline__case_id_d45db9_idx',
            old_name='discipline_d_case_id_9fb4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinecasedecisionsuggestion',
            new_name='discipline__manual__402134_idx',
            old_name='discipline_d_manual__f49dbe_idx',
        ),
        migrations.RenameIndex(
            model_name='manualconvivenciachunk',
            new_name='discipline__manual__a0f0f4_idx',
            old_name='discipline_m_manual_i_0b8d3a_idx',
        ),
    ]
