# Generated by Django 5.2 on 2026-02-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectionProcess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Borrador"), ("OPEN", "Abierta"), ("CLOSED", "Cerrada")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ElectionRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="elections.electionprocess"),
                ),
            ],
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.CreateModel(
            name="ElectionCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("number", models.CharField(max_length=20)),
                ("proposal", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="elections.electionrole"),
                ),
            ],
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.CreateModel(
            name="VoterToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("token_prefix", models.CharField(blank=True, max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("USED", "Usado"),
                            ("REVOKED", "Revocado"),
                            ("EXPIRED", "Expirado"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=255)),
                ("student_grade", models.CharField(blank=True, max_length=30)),
                ("student_shift", models.CharField(blank=True, max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_tokens",
                        to="elections.electionprocess",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="VoteAccessSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "voter_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_sessions",
                        to="elections.votertoken",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_blank", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="elections.voteaccesssession",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votes",
                        to="elections.electioncandidate",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="elections.electionprocess"),
                ),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="elections.electionrole"),
                ),
                (
                    "voter_token",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="elections.votertoken"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="electionrole",
            constraint=models.UniqueConstraint(fields=("process", "code"), name="uniq_election_role_process_code"),
        ),
        migrations.AddConstraint(
            model_name="electioncandidate",
            constraint=models.UniqueConstraint(fields=("role", "number"), name="uniq_election_candidate_role_number"),
        ),
        migrations.AddConstraint(
            model_name="voterecord",
            constraint=models.UniqueConstraint(fields=("voter_token", "role"), name="uniq_vote_per_token_and_role"),
        ),
        migrations.AddConstraint(
            model_name="voterecord",
            constraint=models.UniqueConstraint(fields=("access_session", "role"), name="uniq_vote_per_session_and_role"),
        ),
    ]
