# Generated by Django 5.2 on 2026-02-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenResetEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=500)),
                ("previous_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(default="ACTIVE", max_length=20)),
                ("previous_expires_at", models.DateTimeField(blank=True, null=True)),
                ("new_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reset_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_reset_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_events",
                        to="elections.votertoken",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="votertoken",
            options={
                "ordering": ["-created_at"],
                "permissions": [("reset_votertoken", "Can reset voter token for contingency")],
            },
        ),
    ]
