# Generated by Django 5.2.9 on 2026-02-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_tokenresetevent_votertoken_reset_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidate',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
    ]
