# Generated by Django 5.2.9 on 2026-02-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_electioncandidate_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoContraloria',
            fields=[
            ],
            options={
                'verbose_name': 'Candidato de Contraloría',
                'verbose_name_plural': 'Candidatos de Contraloría',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('elections.electioncandidate',),
        ),
        migrations.CreateModel(
            name='CandidatoPersoneria',
            fields=[
            ],
            options={
                'verbose_name': 'Candidato de Personería',
                'verbose_name_plural': 'Candidatos de Personería',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('elections.electioncandidate',),
        ),
    ]
