# Generated by Django 5.2.9 on 2026-02-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_electionprocesscensusexclusion"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["process", "created_at"], name="evr_proc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["process", "role", "created_at"], name="evr_proc_role_ct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["process", "is_blank", "created_at"],
                name="evr_proc_blank_ct_idx",
            ),
        ),
    ]
