# Generated by Django 5.2 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0010_electionprocess_governance_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votertoken",
            name="token_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="votertoken",
            constraint=models.UniqueConstraint(fields=("process", "token_hash"), name="uniq_votertoken_process_hash"),
        ),
    ]
