# Generated by Django 5.2.9 on 2026-02-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_225c30_idx',
            old_name='users_passw_user_id_3ee25f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_expires_853bc2_idx',
            old_name='users_passw_expires_d12e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_used_at_0c038d_idx',
            old_name='users_passw_used_at_480f1f_idx',
        ),
    ]
