# Generated by Django 5.2.9 on 2025-12-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('level_type', models.CharField(choices=[('PRESCHOOL', 'Preescolar'), ('PRIMARY', 'Básica Primaria'), ('SECONDARY', 'Básica Secundaria'), ('MEDIA', 'Media Académica')], default='PRIMARY', max_length=20)),
                ('min_age', models.PositiveIntegerField(default=5, verbose_name='Edad Mínima')),
                ('max_age', models.PositiveIntegerField(default=100, verbose_name='Edad Máxima')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.PositiveIntegerField(default=100, help_text='Percentage weight within the area')),
                ('hours_per_week', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('PLANNING', 'En Planeación'), ('ACTIVE', 'Activo'), ('CLOSED', 'Finalizado')], default='PLANNING', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LOW', 'Bajo'), ('BASIC', 'Básico'), ('HIGH', 'Alto'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código interno del logro (ej. CN-001)', max_length=20, unique=True)),
                ('description', models.TextField(verbose_name='Descripción del Logro')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_definitions', to='academic.academicload')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_definitions', to='academic.area')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción específica para este periodo (puede heredar del banco)')),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Porcentaje de valoración si aplica')),
                ('academic_load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academic.academicload')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='academic.achievementdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_percentage', models.PositiveIntegerField(help_text='Percentage weight within the subject')),
                ('academic_load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='academic.academicload')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('weight_percentage', models.PositiveIntegerField(default=100, help_text='Percentage weight within the component')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academic.evaluationcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True)),
                ('scale_type', models.CharField(choices=[('NUMERIC', 'Numérica (Básica/Media)'), ('QUALITATIVE', 'Cualitativa (Preescolar)')], default='NUMERIC', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scales', to='academic.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academic.academiclevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='achievementdefinition',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_definitions', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='academicload',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='academic.grade'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shift', models.CharField(choices=[('MORNING', 'Mañana'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('FULL', 'Jornada Única'), ('WEEKEND', 'Fin de Semana')], default='MORNING', max_length=20)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Cupo Máximo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academic.academicyear')),
            ],
        ),
    ]
