# Generated by Django 5.2.9 on 2025-12-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='performanceindicator',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='academic.achievement'),
        ),
        migrations.AddField(
            model_name='period',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.assessment'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.area'),
        ),
        migrations.AddField(
            model_name='academicload',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='academic_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.academicload'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.group'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'grade', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='performanceindicator',
            unique_together={('achievement', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('assessment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='academicload',
            unique_together={('subject', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('academic_load', 'group', 'academic_year')},
        ),
    ]
