# Generated by Django 5.2.9 on 2025-12-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_area_group_period_subject_teacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_percentage', models.PositiveIntegerField(help_text='Percentage weight within the subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('weight_percentage', models.PositiveIntegerField(default=100, help_text='Percentage weight within the component')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.period')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academic.evaluationcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scales', to='academic.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feedback', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.assessment')),
            ],
        ),
    ]
