# Generated by Django 5.2.9 on 2025-12-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementdefinition',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_definitions', to='academic.subject'),
        ),
    ]
