# Generated by Django 5.2.9 on 2025-12-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_studentgrade_student_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('level_type', models.CharField(choices=[('PRESCHOOL', 'Preescolar'), ('PRIMARY', 'Básica Primaria'), ('SECONDARY', 'Básica Secundaria'), ('MEDIA', 'Media Académica')], default='PRIMARY', max_length=20)),
                ('min_age', models.PositiveIntegerField(default=5, verbose_name='Edad Mínima')),
                ('max_age', models.PositiveIntegerField(default=100, verbose_name='Edad Máxima')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.campus'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academic.academiclevel'),
        ),
    ]
