# Generated by Django 6.0 on 2025-12-10 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_achievementdefinition_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Peso porcentual en la nota definitiva', verbose_name='Porcentaje')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='academic.academicyear')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'unique_together': {('academic_year', 'name')},
            },
        ),
    ]
