# Generated by Django 5.2.9 on 2025-12-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_academiclevel_group_campus_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Mañana'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('FULL', 'Jornada Única'), ('WEEKEND', 'Fin de Semana')], default='MORNING', max_length=20),
        ),
    ]
