# Generated by Django 5.2.9 on 2025-12-10 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='academic.dimension'),
        ),
    ]
