# Generated by Django 5.2.9 on 2025-12-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_group_classroom_group_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationscale',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationscale',
            name='scale_type',
            field=models.CharField(choices=[('NUMERIC', 'Numérica (Básica/Media)'), ('QUALITATIVE', 'Cualitativa (Preescolar)')], default='NUMERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationscale',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationscale',
            name='min_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
