# Generated by Django 5.2.9 on 2025-12-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_achievement_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementdefinition',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_definitions', to='academic.dimension'),
        ),
    ]
