# Generated by Django 5.2.9 on 2025-12-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_evaluationscale_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'En Planeación'), ('ACTIVE', 'Activo'), ('CLOSED', 'Finalizado')], default='PLANNING', max_length=20, verbose_name='Estado'),
        ),
    ]
