# Generated by Django 5.2.9 on 2025-12-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_achievementdefinition_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academic.group'),
        ),
    ]
