# Generated by Django 5.2.9 on 2025-12-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_achievement_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academic.subject'),
        ),
    ]
