# Generated by Django 5.2.9 on 2025-12-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_academicyear_end_date_academicyear_start_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('subject', 'group', 'academic_year')},
        ),
    ]
