# Generated by Django 5.2.9 on 2025-12-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_achievement_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Logro Planificado', 'verbose_name_plural': 'Logros Planificados'},
        ),
        migrations.AlterModelOptions(
            name='achievementdefinition',
            options={'verbose_name': 'Banco de Logros', 'verbose_name_plural': 'Banco de Logros'},
        ),
        migrations.AlterModelOptions(
            name='performanceindicator',
            options={'verbose_name': 'Indicador de Desempeño', 'verbose_name_plural': 'Indicadores de Desempeño'},
        ),
    ]
