# Generated by Django 5.2.9 on 2025-12-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_teacherassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=40, verbose_name='Cupo Máximo'),
        ),
    ]
