# Generated by GitHub Copilot on 2025-12-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
        ("academic", "0010_alter_achievement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Borrador"), ("PUBLISHED", "Publicado")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_sheets",
                        to="academic.period",
                    ),
                ),
                (
                    "teacher_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_sheets",
                        to="academic.teacherassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planilla de Calificaciones",
                "verbose_name_plural": "Planillas de Calificaciones",
            },
        ),
        migrations.CreateModel(
            name="AchievementGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_grades",
                        to="academic.achievement",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_grades",
                        to="students.enrollment",
                    ),
                ),
                (
                    "gradesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_grades",
                        to="academic.gradesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota por Logro",
                "verbose_name_plural": "Notas por Logro",
            },
        ),
        migrations.AddConstraint(
            model_name="gradesheet",
            constraint=models.UniqueConstraint(
                fields=("teacher_assignment", "period"),
                name="uniq_grade_sheet_assignment_period",
            ),
        ),
        migrations.AddIndex(
            model_name="gradesheet",
            index=models.Index(
                fields=["teacher_assignment", "period"],
                name="idx_gradesheet_assign_period",
            ),
        ),
        migrations.AddIndex(
            model_name="gradesheet",
            index=models.Index(fields=["period"], name="idx_gradesheet_period"),
        ),
        migrations.AddConstraint(
            model_name="achievementgrade",
            constraint=models.UniqueConstraint(
                fields=("gradesheet", "enrollment", "achievement"),
                name="uniq_achievement_grade_cell",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementgrade",
            index=models.Index(
                fields=["gradesheet", "enrollment"],
                name="idx_achgrade_sheet_enr",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementgrade",
            index=models.Index(
                fields=["gradesheet", "achievement"],
                name="idx_achgrade_sheet_ach",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementgrade",
            index=models.Index(fields=["enrollment"], name="idx_achgrade_enrollment"),
        ),
    ]
