# Generated by Django 6.0 on 2025-12-26 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_gradebook_models'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='grades_edit_until',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora límite para que docentes editen planillas/notas en este periodo (si está vacío, queda abierto).', null=True, verbose_name='Edición de notas hasta'),
        ),
        migrations.AddField(
            model_name='period',
            name='planning_edit_until',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora límite para que docentes editen planeación en este periodo (si está vacío, queda abierto).', null=True, verbose_name='Edición de planeación hasta'),
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GRADES', 'Planillas/Notas'), ('PLANNING', 'Planeación')], max_length=20)),
                ('request_type', models.CharField(choices=[('FULL', 'Toda la planilla'), ('PARTIAL', 'Parcial (por estudiante)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('requested_until', models.DateTimeField(blank=True, help_text='Hasta cuándo solicita permiso. Si está vacío, el aprobador definirá el plazo.', null=True)),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='academic.period')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(blank=True, help_text='Requerido para solicitudes de notas; opcional para planeación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='academic.teacherassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GRADES', 'Planillas/Notas'), ('PLANNING', 'Planeación')], max_length=20)),
                ('grant_type', models.CharField(choices=[('FULL', 'Toda la planilla'), ('PARTIAL', 'Parcial (por estudiante)')], max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_edit_grants', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='edit_grants', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_grants', to='academic.period')),
                ('teacher_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_grants', to='academic.teacherassignment')),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='academic.editrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditGrantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_grant_items', to='students.enrollment')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.editgrant')),
            ],
            options={
                'unique_together': {('grant', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='EditRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(help_text='Estudiante (matrícula) afectado por una solicitud parcial.', on_delete=django.db.models.deletion.CASCADE, related_name='edit_request_items', to='students.enrollment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.editrequest')),
            ],
            options={
                'unique_together': {('request', 'enrollment')},
            },
        ),
    ]
