# Generated by Django 5.2.9 on 2025-12-31 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_period_grades_edit_until_period_planning_edit_until_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['ordinal', 'name']},
        ),
        migrations.AddField(
            model_name='grade',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, help_text='Orden de progresión institucional (ej: Jardín=1 ... Undécimo=13).', null=True),
        ),
        migrations.CreateModel(
            name='EnrollmentPromotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PROMOTED', 'Promoción plena'), ('CONDITIONAL', 'Promoción condicional'), ('REPEATED', 'Repitencia'), ('GRADUATED', 'Graduado')], max_length=20)),
                ('failed_subjects_count', models.PositiveIntegerField(default=0)),
                ('failed_areas_count', models.PositiveIntegerField(default=0)),
                ('failed_subjects_distinct_areas_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('sealed_hash', models.CharField(blank=True, max_length=128)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_snapshot', to='students.enrollment')),
            ],
            options={
                'verbose_name': 'Resultado anual de promoción',
                'verbose_name_plural': 'Resultados anuales de promoción',
            },
        ),
    ]
