# Generated by GitHub Copilot on 2026-01-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0014_alter_grade_ordinal_integer_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradesheet",
            name="grading_mode",
            field=models.CharField(
                choices=[
                    ("ACHIEVEMENT", "Tradicional (nota por logro)"),
                    ("ACTIVITIES", "Actividades (promedio hacia logro)"),
                ],
                default="ACHIEVEMENT",
                max_length=20,
                verbose_name="Modo de calificación",
            ),
        ),
        migrations.CreateModel(
            name="AchievementActivityColumn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_columns",
                        to="academic.achievement",
                    ),
                ),
                (
                    "gradesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_columns",
                        to="academic.gradesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Columna de actividad (logro)",
                "verbose_name_plural": "Columnas de actividad (logro)",
            },
        ),
        migrations.CreateModel(
            name="AchievementActivityGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academic.achievementactivitycolumn",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_activity_grades",
                        to="students.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de actividad (logro)",
                "verbose_name_plural": "Notas de actividad (logro)",
            },
        ),
        migrations.AddConstraint(
            model_name="achievementactivitycolumn",
            constraint=models.UniqueConstraint(
                fields=("gradesheet", "achievement", "order"),
                name="uniq_activitycol_sheet_ach_order",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementactivitycolumn",
            index=models.Index(fields=["gradesheet", "achievement"], name="idx_activitycol_sheet_ach"),
        ),
        migrations.AddIndex(
            model_name="achievementactivitycolumn",
            index=models.Index(fields=["gradesheet"], name="idx_activitycol_sheet"),
        ),
        migrations.AddConstraint(
            model_name="achievementactivitygrade",
            constraint=models.UniqueConstraint(
                fields=("column", "enrollment"),
                name="uniq_activitygrade_col_enr",
            ),
        ),
        migrations.AddIndex(
            model_name="achievementactivitygrade",
            index=models.Index(fields=["column", "enrollment"], name="idx_activitygrade_col_enr"),
        ),
        migrations.AddIndex(
            model_name="achievementactivitygrade",
            index=models.Index(fields=["enrollment"], name="idx_activitygrade_enrollment"),
        ),
    ]
