# Generated by Django 5.2.9 on 2026-01-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0015_gradebook_activity_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementdefinition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó este logro en el banco.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achievement_definitions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
