# Generated by Django 5.2.9 on 2026-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0016_achievementdefinition_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_multigrade",
            field=models.BooleanField(default=False),
        ),
    ]
