# Generated by Django 5.2.9 on 2026-01-29 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0017_group_is_multigrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementgrade",
            name="qualitative_scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achievement_grades_qualitative",
                to="academic.evaluationscale",
            ),
        ),
        migrations.AddField(
            model_name="evaluationscale",
            name="applies_to_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRESCHOOL", "Preescolar"),
                    ("BASIC", "Básica"),
                    ("MIDDLE", "Media"),
                ],
                help_text="Nivel al que aplica (ej. PRESCHOOL).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evaluationscale",
            name="internal_numeric_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Equivalente numérico interno (opcional).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evaluationscale",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Escala por defecto para el nivel/año."
            ),
        ),
        migrations.AddField(
            model_name="evaluationscale",
            name="order",
            field=models.PositiveIntegerField(
                default=1, help_text="Orden para etiquetas cualitativas."
            ),
        ),
        migrations.AlterField(
            model_name="gradesheet",
            name="grading_mode",
            field=models.CharField(
                choices=[
                    ("ACHIEVEMENT", "Tradicional (nota por logro)"),
                    ("ACTIVITIES", "Actividades (promedio hacia logro)"),
                    ("QUALITATIVE", "Preescolar (cualitativa)"),
                ],
                default="ACHIEVEMENT",
                max_length=20,
                verbose_name="Modo de calificación",
            ),
        ),
    ]
