# Generated by Django 5.2.9 on 2026-02-15 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0018_achievementgrade_qualitative_scale_and_more"),
        ("core", "0006_alter_institution_pdf_rector_signature_image"),
        ("students", "0010_alter_studentdocument_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("EVALUATION", "Comisión de Evaluación"),
                            ("PROMOTION", "Comisión de Promoción"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("IN_PROGRESS", "En curso"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="academic.group",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="core.institution",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="academic.period",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommissionStudentDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failed_subjects_count", models.PositiveSmallIntegerField(default=0)),
                ("failed_areas_count", models.PositiveSmallIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMMITMENT", "Compromiso"),
                            ("FOLLOW_UP", "Seguimiento"),
                            ("CLOSED", "Cerrado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_decisions",
                        to="academic.commission",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_student_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_decisions",
                        to="students.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_flagged", "enrollment_id"],
                "unique_together": {("commission", "enrollment")},
            },
        ),
        migrations.CreateModel(
            name="CommitmentActa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("GENERATED", "Generada")],
                        default="GENERATED",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("commitments", models.TextField(blank=True)),
                ("student_name", models.CharField(max_length=200)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                ("director_name", models.CharField(blank=True, max_length=200)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_acta",
                        to="academic.commissionstudentdecision",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commitment_actas_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observer_annotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_actas",
                        to="students.observerannotation",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjects_threshold", models.PositiveSmallIntegerField(default=2)),
                ("areas_threshold", models.PositiveSmallIntegerField(default=2)),
                (
                    "operator",
                    models.CharField(
                        choices=[("OR", "OR"), ("AND", "AND")],
                        default="OR",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rule_configs",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rule_configs",
                        to="core.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__year", "id"],
                "unique_together": {("institution", "academic_year")},
            },
        ),
    ]
