# Generated by Django 5.2.11 on 2026-03-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0021_alter_classplan_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="periodtopic",
            name="uniq_period_topic_order_per_load",
        ),
    ]
