# Generated by Django 5.2.9 on 2025-12-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Institución')),
                ('dane_code', models.CharField(blank=True, max_length=50, verbose_name='Código DANE')),
                ('nit', models.CharField(blank=True, max_length=50, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección Principal')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('rector_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Rector')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Sede')),
                ('dane_code', models.CharField(blank=True, max_length=50, verbose_name='Código DANE Sede')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es Sede Principal')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.institution')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
    ]
