# Generated by Django 5.2.9 on 2025-12-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Código DANE Actual')),
                ('dane_code_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='Código DANE Anterior')),
                ('sede_number', models.CharField(blank=True, default='01', help_text='Ej: 01, 02, 03...', max_length=10, verbose_name='Número de Sede')),
                ('nit', models.CharField(blank=True, default='', max_length=50, verbose_name='NIT')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Sede')),
                ('sede_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('ANEXA', 'Anexa'), ('RURAL_DISPERSA', 'Rural Dispersa'), ('URBANA', 'Urbana')], default='PRINCIPAL', max_length=20, verbose_name='Tipo de Sede')),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('EN_REAPERTURA', 'En Reapertura')], default='ACTIVA', max_length=20, verbose_name='Estado de la Sede')),
                ('resolution_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Resolución de Aprobación')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('character', models.CharField(choices=[('ACADEMICA', 'Académica'), ('TECNICA', 'Técnica'), ('TECNICA_ACADEMICA', 'Técnica y Académica')], default='ACADEMICA', max_length=20, verbose_name='Carácter')),
                ('specialty', models.CharField(choices=[('ACADEMICO', 'Académico'), ('TECNICO', 'Técnico'), ('ARTISTICO', 'Artístico'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('AGROPECUARIO', 'Agropecuario'), ('PEDAGOGICO', 'Pedagógico')], default='ACADEMICO', max_length=20, verbose_name='Especialidad')),
                ('methodology', models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('ESCUELA_NUEVA', 'Escuela Nueva'), ('ACELERACION', 'Aceleración del Aprendizaje'), ('POST_PRIMARIA', 'Post Primaria'), ('TELESECUNDARIA', 'Telesecundaria'), ('SAT', 'SAT'), ('CAFAM', 'CAFAM'), ('A_CRECER', 'A Crecer')], default='TRADICIONAL', max_length=20, verbose_name='Metodología')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento')),
                ('municipality', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio')),
                ('zone', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], default='URBANA', max_length=10, verbose_name='Zona')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=200, verbose_name='Vereda o Barrio')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('levels', models.JSONField(default=list, help_text='Lista de niveles: PREESCOLAR, BASICA_PRIMARIA, BASICA_SECUNDARIA, MEDIA', verbose_name='Niveles que Ofrece')),
                ('shifts', models.JSONField(default=list, help_text='Lista de jornadas: MANANA, TARDE, NOCHE, UNICA, FIN_SEMANA', verbose_name='Jornadas')),
                ('calendar', models.CharField(choices=[('A', 'Calendario A'), ('B', 'Calendario B')], default='A', max_length=1, verbose_name='Calendario')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono Fijo')),
                ('mobile', models.CharField(blank=True, default='', max_length=50, verbose_name='Celular de Contacto')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Institucional de Sede')),
                ('other_contact', models.CharField(blank=True, default='', max_length=200, verbose_name='Otro Medio de Contacto')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es Sede Principal')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['sede_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Institución')),
                ('dane_code', models.CharField(blank=True, max_length=50, verbose_name='Código DANE')),
                ('nit', models.CharField(blank=True, max_length=50, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección Principal')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Escudo/Logo')),
            ],
        ),
    ]
