# Generated by Django 5.2.9 on 2025-12-08 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='rector_name',
        ),
        migrations.AddField(
            model_name='institution',
            name='rector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'TEACHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Rector'),
        ),
        migrations.AddField(
            model_name='institution',
            name='secretary',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Secretario/a'),
        ),
    ]
