# Generated by Django 5.2.9 on 2025-12-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='campus_secretary',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Secretario(a)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador(a)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'TEACHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Rector(a) o Director(a)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='rector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'TEACHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Rector'),
        ),
        migrations.AddField(
            model_name='institution',
            name='secretary',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Secretario/a'),
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.institution', verbose_name='Institución'),
        ),
    ]
