# Generated by Django 5.2.9 on 2025-12-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_institution_rector_name_institution_rector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Escudo/Logo'),
        ),
    ]
