# Generated by Django 5.2.9 on 2025-12-08 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['sede_number', 'name'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AddField(
            model_name='campus',
            name='calendar',
            field=models.CharField(choices=[('A', 'Calendario A'), ('B', 'Calendario B')], default='A', max_length=1, verbose_name='Calendario'),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_secretary',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SECRETARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Secretario(a)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='character',
            field=models.CharField(choices=[('ACADEMICA', 'Académica'), ('TECNICA', 'Técnica'), ('TECNICA_ACADEMICA', 'Técnica y Académica')], default='ACADEMICA', max_length=20, verbose_name='Carácter'),
        ),
        migrations.AddField(
            model_name='campus',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador(a)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='dane_code_previous',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código DANE Anterior'),
        ),
        migrations.AddField(
            model_name='campus',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='campus',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'TEACHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_campuses', to=settings.AUTH_USER_MODEL, verbose_name='Rector(a) o Director(a)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Institucional de Sede'),
        ),
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='campus',
            name='levels',
            field=models.JSONField(default=list, help_text='Lista de niveles: PREESCOLAR, BASICA_PRIMARIA, BASICA_SECUNDARIA, MEDIA', verbose_name='Niveles que Ofrece'),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='campus',
            name='methodology',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('ESCUELA_NUEVA', 'Escuela Nueva'), ('ACELERACION', 'Aceleración del Aprendizaje'), ('POST_PRIMARIA', 'Post Primaria'), ('TELESECUNDARIA', 'Telesecundaria'), ('SAT', 'SAT'), ('CAFAM', 'CAFAM'), ('A_CRECER', 'A Crecer')], default='TRADICIONAL', max_length=20, verbose_name='Metodología'),
        ),
        migrations.AddField(
            model_name='campus',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Celular de Contacto'),
        ),
        migrations.AddField(
            model_name='campus',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='campus',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Vereda o Barrio'),
        ),
        migrations.AddField(
            model_name='campus',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='campus',
            name='other_contact',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Otro Medio de Contacto'),
        ),
        migrations.AddField(
            model_name='campus',
            name='resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AddField(
            model_name='campus',
            name='resolution_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Resolución de Aprobación'),
        ),
        migrations.AddField(
            model_name='campus',
            name='sede_number',
            field=models.CharField(blank=True, default='01', help_text='Ej: 01, 02, 03...', max_length=10, verbose_name='Número de Sede'),
        ),
        migrations.AddField(
            model_name='campus',
            name='sede_type',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('ANEXA', 'Anexa'), ('RURAL_DISPERSA', 'Rural Dispersa'), ('URBANA', 'Urbana')], default='PRINCIPAL', max_length=20, verbose_name='Tipo de Sede'),
        ),
        migrations.AddField(
            model_name='campus',
            name='shifts',
            field=models.JSONField(default=list, help_text='Lista de jornadas: MANANA, TARDE, NOCHE, UNICA, FIN_SEMANA', verbose_name='Jornadas'),
        ),
        migrations.AddField(
            model_name='campus',
            name='specialty',
            field=models.CharField(choices=[('ACADEMICO', 'Académico'), ('TECNICO', 'Técnico'), ('ARTISTICO', 'Artístico'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('AGROPECUARIO', 'Agropecuario'), ('PEDAGOGICO', 'Pedagógico')], default='ACADEMICO', max_length=20, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='campus',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('EN_REAPERTURA', 'En Reapertura')], default='ACTIVA', max_length=20, verbose_name='Estado de la Sede'),
        ),
        migrations.AddField(
            model_name='campus',
            name='zone',
            field=models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], default='URBANA', max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='dane_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código DANE Actual'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Sede'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono Fijo'),
        ),
    ]
