# Generated by Django 5.2.9 on 2026-01-15 04:49

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_institution_certificate_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='pdf_rector_signature_image',
            field=models.ImageField(blank=True, help_text='Debe ser PNG (idealmente con fondo transparente) para usar en certificados/reportes.', null=True, upload_to='institutions/signatures/', validators=[django.core.validators.FileExtensionValidator(['png']), core.models.validate_png_image], verbose_name='Firma del rector (PDF)'),
        ),
    ]
